# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  user,
  ...
}: {
  imports = [
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "usbcore"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "usbcore" "snd-seq" "snd-rawmidi"];
  boot.blacklistedKernelModules = ["amdgpu"];
  boot.extraModulePackages = [];
  boot.kernelParams = [
    "boot.shell_on_fail"
    "acpi_backlight=vendor"
    "video.use_native_backlight=1"
  ];
  boot.tmp.useTmpfs = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  hardware.openrazer.enable = true;
  environment.systemPackages = with pkgs; [
    openrazer-daemon
    polychromatic
    razergenie
  ];
  users.users.${user} = {...}: {
    extraGroups = ["openrazer"];
  };


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
}
