# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  minecraft-bedrock-server = {
    pname = "minecraft-bedrock-server";
    version = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.30.03.zip";
    src = fetchurl {
      url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.30.03.zip";
      sha256 = "sha256-kYCtr1/7d0yBFyAtzNq9kEyi2DfqmmBDJ1snhWhHD/U=";
    };
  };
}
