# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  minecraft-bedrock-server = {
    pname = "minecraft-bedrock-server";
    version = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.20.03.zip";
    src = fetchurl {
      url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.20.03.zip";
      sha256 = "sha256-vvJrQDQvsGFHpaN/pRckxajsp3BSCU+iZWL9dx26U9U=";
    };
  };
}
