# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  minecraft-bedrock-server = {
    pname = "minecraft-bedrock-server";
    version = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.22.01.zip";
    src = fetchurl {
      url = "https://minecraft.azureedge.net/bin-linux/bedrock-server-1.21.22.01.zip";
      sha256 = "sha256-hRqTWW/mshLgKeW0xjiCyXQXIpBeWTzYHD4A+dD3i+E=";
    };
  };
}
