# [minecraft-bedrock-server]
# src.github = "bedrock-crustaceans/RAstra"
# src.git = 'https://github.com/bedrock-crustaceans/RAstra.git'
# fetch.github = "bedrock-crustaceans/RAstra"
# fetch.git = "https://github.com/bedrock-crustaceans/RAstra.git"
