# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl_shimeji = {
    pname = "wl_shimeji";
    version = "9bc41cf573ab9adb13ebc88870d2b18503e8ff2d";
    src = fetchFromGitHub {
      owner = "CluelessCatBurger";
      repo = "wl_shimeji";
      rev = "9bc41cf573ab9adb13ebc88870d2b18503e8ff2d";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-jn3GLa+917x/446Auy1Y5BY7OcjNeA+e0zBwf65c6ao=";
    };
    date = "2025-07-01";
  };
}
