# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl_shimeji = {
    pname = "wl_shimeji";
    version = "fbb2e148981386863410f4fadecc240af6dc9e6a";
    src = fetchFromGitHub {
      owner = "CluelessCatBurger";
      repo = "wl_shimeji";
      rev = "fbb2e148981386863410f4fadecc240af6dc9e6a";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ftDWTEAZBz7jug/PbvU4+ANRcsP1kUF4zLvX0zWBUwY=";
    };
    date = "2025-04-04";
  };
}
