# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  wl_shimeji = {
    pname = "wl_shimeji";
    version = "d973b1a9fe0942c5a29d764c2b1983c37029a42e";
    src = fetchFromGitHub {
      owner = "CluelessCatBurger";
      repo = "wl_shimeji";
      rev = "d973b1a9fe0942c5a29d764c2b1983c37029a42e";
      fetchSubmodules = true;
      deepClone = true;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Le0zdfHDjVNKUvXQw2mzqySzmOsZdLOD2dCzxAr1gHE=";
    };
    date = "2025-08-03";
  };
}
