[package]
name = "dotfiles_utils"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.4.4", features = ["derive", "string"] }
csv = "1.3.0"
dirs = "5.0.1"
execute = "0.2.13"
rand = "0.8.5"
rayon = "1.9.0"
regex = "1.10.3"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
sysinfo = "0.30.5"

[build-dependencies]
clap = { version = "4.4.4", features = ["derive", "string"] }
clap_complete = "4.4.3"

[features]
default = ["hyprland"]
hyprland = []

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
missing_errors_doc = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
must_use_candidate = { level = "allow", priority = 1 }
nursery = "deny"
option_if_let_else = { level = "allow", priority = 1 }
unwrap_used = "deny"

[profile.release]
strip = true
lto = true
