# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  hyprcursor = {
    pname = "hyprcursor";
    version = "ac903e80b33ba6a88df83d02232483d99f327573";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprcursor";
      rev = "ac903e80b33ba6a88df83d02232483d99f327573";
      fetchSubmodules = false;
      sha256 = "sha256-lzTV10FJTCGNtMdgW5YAhCAqezeAzKOd/97HbQK8GTU=";
    };
    date = "2025-04-29";
  };
  hyprlock = {
    pname = "hyprlock";
    version = "da1d076d849fc0f298c1d287bddd04802bf7d0f9";
    src = fetchFromGitHub {
      owner = "hyprwm";
      repo = "hyprlock";
      rev = "da1d076d849fc0f298c1d287bddd04802bf7d0f9";
      fetchSubmodules = false;
      sha256 = "sha256-IypoV7crmhQ4llD0n4qqO4XTRNAAbHfA+2oiTiq2qpk=";
    };
    date = "2025-05-19";
  };
  swww = {
    pname = "swww";
    version = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
    src = fetchFromGitHub {
      owner = "LGFae";
      repo = "swww";
      rev = "432b7135af0bb34e4b0e55edf76ff516937bc7b0";
      fetchSubmodules = false;
      sha256 = "sha256-pX6fJrlNXe1W5ZO9nC9ikN1zoAcHDqErLS7EnglD33o=";
    };
  };
  wallust = {
    pname = "wallust";
    version = "c3900a3a42ea1d05487867d0f723629cbee3a506";
    src = fetchgit {
      url = "https://codeberg.org/explosion-mental/wallust.git";
      rev = "c3900a3a42ea1d05487867d0f723629cbee3a506";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7/6Yc0futrWIm1+Qh/Km8tKj/JxKFLidbSIa+9YYIrA=";
    };
    date = "2025-05-22";
  };
}
