[swww]
src.git = "https://github.com/Horus645/swww"
fetch.github = "Horus645/swww"

[transmission-web-soft-theme]
src.git = "https://github.com/diesys/transmission-web-soft-theme"
fetch.github = "diesys/transmission-web-soft-theme"

[wallust]
src.git = "https://codeberg.org/explosion-mental/wallust.git"
src.branch = "dev"
fetch.git = "https://codeberg.org/explosion-mental/wallust.git"

[waybar]
src.git = "https://github.com/Alexays/Waybar"
fetch.github = "Alexays/Waybar"

[wezterm]
src.git = "https://github.com/wez/wezterm"
fetch.github = "wez/wezterm"
git.fetchSubmodules = true

[goo-engine]
src.git = "https://github.com/dillongoostudios/goo-engine"
fetch.github = "dillongoostudios/goo-engine"
git.fetchSubmodules = false
