# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  terrafirmagreg = {
    pname = "terrafirmagreg";
    version = "0.7.12";
    src = fetchurl {
      url = "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/releases/download/0.7.12/TerraFirmaGreg-1.20.x-0.7.12-server.zip";
      sha256 = "sha256-Ts9Vseb76ALNDbVFbLHUlH3kfIN5S3b8b2XHTCqs9KQ=";
    };
  };
}
