[terrafirmagreg]
src.github = "TerraFirmaGreg-Team/Modpack-Modern"
fetch.url = "https://github.com/TerraFirmaGreg-Team/Modpack-Modern/releases/download/0.8.1/TerraFirmaGreg-Modern-0.8.1-serverpack.zip"
