# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  goo-engine = {
    pname = "goo-engine";
    version = "2d3f5fb09f3d66de1ed2a3481bc1301469170e11";
    src = fetchFromGitHub {
      owner = "dillongoostudios";
      repo = "goo-engine";
      rev = "2d3f5fb09f3d66de1ed2a3481bc1301469170e11";
      fetchSubmodules = false;
      sha256 = "sha256-L5abwhj8tLKFOemSZzAa4U2lwOHE/G2eKNfoTAY17Ek=";
    };
    date = "2024-01-30";
  };
}
