# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  goo-engine = {
    pname = "goo-engine";
    version = "9d27635972055084ea82017d864dbcd1ea26a058";
    src = fetchFromGitHub {
      owner = "dillongoostudios";
      repo = "goo-engine";
      rev = "9d27635972055084ea82017d864dbcd1ea26a058";
      fetchSubmodules = false;
      sha256 = "sha256-Mld6On+HkNSpvqTV7hfiUQqxby0zZ2Ldc+LWW67jSkY=";
    };
    date = "2023-11-11";
  };
}
